steps:
- task: Npm@1
  displayName: 'npm publish'
  inputs:
    command: publish
    workingDir: '$(System.DefaultWorkingDirectory)/jsrep/drop'
    verbose: false
    publishRegistry: useFeed
    publishFeed: '34c483d6-43e2-4487-ae1a-4310f09837c3'